language: cpp

# Build matrix.
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang

# Build dependencies. (Linux)
# NOTE: KF5 is not available on Ubuntu 14.04,
# so we can't build the KF5 plugin.
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libpng-dev
      - libjpeg-dev
      - nettle-dev
      - libtinyxml2-dev
      - libqt4-dev
      - kdelibs5-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libthunarx-2-dev
      - libgtk-3-dev
      - libnautilus-extension-dev
      - gettext
      - libnemo-extension-dev
      - libseccomp-dev
      #- libzstd-dev
      - liblz4-dev
      - liblzo2-dev
      - libcanberra-dev
      - libcanberra-gtk-dev
      - libcanberra-gtk3-dev

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
