language: cpp

# Compiler selection.
compiler:
  - clang
  - gcc

# Use Ubuntu 14.04 as the build environment.
sudo: required
dist: trusty

# Build dependencies.
# NOTE: KF5 is not available on Ubuntu 14.04,
# so we can't build the KDE5 plugin.
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libpng-dev
      - libqt4-dev
      - kdelibs5-dev
      - nettle-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libthunarx-2-dev
      - libgtk-3-dev
      - libnautilus-extension-dev
      - libjpeg-dev

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
